# Generated by Django 3.1.7 on 2023-02-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20230205_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
