# Generated by Django 3.1.7 on 2023-03-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
    ]
